#!/bin/sh

cd -P "$(dirname $0)"

client_message "Deploying sahara (action_hooks=deply)..."

source $OPENSHIFT_CARTRIDGE_SDK_BASH

createCluster "${OPENSHIFT_REPO_DIR}cluster/config.properties"
deployJob "${OPENSHIFT_REPO_DIR}cluster/config.properties"